### ISSUE TITLE
python3.6 导入 FullLoader 时出现错误

### ISSUE THREAD

**Issue by sorrymyself** [xtaodada/PagerMaid-Modify#1]
运行出现这个，依赖什么的都装了

`File "/usr/local/bin/pagermaid", line 7, in <module>     from pagermaid import __main__   File "/usr/local/lib/python3.6/dist-packages/pagermaid/__init__.py", line 6, in <module>     from yaml import load, FullLoader ImportError: cannot import name 'FullLoader'`

**Comment by xtaodada** [comment]
请尝试通过升级 `pyyaml` 包来解决此问题 🧐

```
pip3 install --upgrade pip

pip3 install --upgrade pyyaml
```

**Comment by sorrymyself** [comment]
谢谢！

**Comment by xtaodada** [comment]
OK 😉

**Comment by sorrymyself** [comment]
> 好 😉

提醒下各位，ubuntu貌似很容易有这个问题，通过升级pip3 和安装pyyaml解决，但是安装pyyaml如果错误，执行一下
sudo -H pip3 install --ignore-installed PyYAML
就完美解决了

**Comment by sorrymyself** [comment]
偷取贴纸时，出现了这个错误

An error occurred while executing this command.

**Comment by xtaodada** [comment]
出现英文报错是原版 Pagermaid ，您可以在 telegram 任意对话中使用 `-source` 前往原作者 repo 提问，或者直接贴出 运行目录下最新的 `exception.****.pagermaid` 。

**Comment by sorrymyself** [comment]
谢谢，我尝试一下


Xtao_dada <notifications@github.com> 于2020年4月5日周日 上午12:17写道：

**Comment by sorrymyself** [comment]
以下是提取到的文字:
weevoausunn



# Generated: 16:55 04/04/2020
# ChatID: -1001342206582
# UserID: 740265946.
# Message:
EGIN TARGET MESSAGE-
-sticker
-----END TARGET MESSAGE
# Traceback:
~----BEGIN TRACEBACK-----
Traceback (most recent call last)
File "/var/lib/PagerMaid-Modify/pagermaid/listener.py", line 54, in handler
await function(context)
File "/var/lib/PagerMaid-Modify/pagermaid/modules/sticker.py", line 83, in sticker
request .Request (f ‘http: //t.me/addstickers/{pack_name}'))
File "/usr/lib/python3.6/urllib/request.py", Line 223, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.6/urllib/request.py", line 526, in open
response = self. open(req, data)
File "/usr/lib/python3.6/urilib/request.py", line 544, in _open
‘open’, req)
File "/usr/lib/python3.6/urllib/request.py", line 564, in _call_chain
result = func(*args)
File "/usr/lib/python3.6/urllib/request.py", Line 1346, in http_open
return self.do_open(http.client.HTTPConnection, req)
File "/usr/lib/python3.6/urllib/request.py", Line 1318, in do_open
encode_chunked=req.has_header('Transfer-encoding'))
File "/usr/lib/python3.6/http/client.py", line 1254, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/isr/Lib/python3.6/nttp/client.py", line 1265, in _send_request
self.putrequest (method, url, **skips)
File "/usr/Lib/python3.6/http/client.py", line 1132, in putrequest
self ._output (request .encode(‘ascii'))
UnicodeEncodeError: ‘ascii’ codec can't encode characters in position 17-19: ordinal not in range(128)










-----END TRACEBACK-----
# Error: "tascii' codec can't encode characters in position 17-19: ordinal not in range(128)".

这是日志，我不太懂是啥意思
2020年4月5日 +0800 00:17 Xtao_dada <notifications@github.com>，写道：

**Comment by xtaodada** [comment]
@sorrymyself 出现此错误可能是由于您未设置 username 或者您的 姓 中出现了不属于 ASCII 的字符，建议调整一下 姓 或者设置 username 即可

**Comment by sorrymyself** [comment]
是的，我弄了一个命令，把我用户名取消了，之后才注意到，被自己蠢哭
2020年4月5日 +0800 08:05 Xtao_dada <notifications@github.com>，写道：

**Comment by xtaodada** [comment]
@sorrymyself OK 😉 推荐在使用之前查一下帮助 比如 `-help aaa`  。

PagerMaid_Modify 中文翻译还在优化中，您可以使用 -update 来更新最新版本。

更新后推荐使用 `-chat` 命令来加入用户群（主要是一些扩展和反馈），或者 [手动加群](https://t.me/PagerMaid_Modify)
