### ISSUE TITLE
功能建议：关于私聊转发bot / 24小时在线

### ISSUE THREAD

**Issue by LucifinilCn** [xtaodada/PagerMaid-Modify#11]
我先澄清下，我是铁打的小白（多谢wiki的教程，让我在ubuntu上复制/粘贴/回车顺利使用了Pagermaid）

================单纯的分割线================

【关于私聊转发bot】
其实Telegram上有私聊 转发bot（@Livegram）但是前些日子老炸，经常几个小时不能用。

碰巧使用第三方Telegram（APP：Nekogram）发现有个机器人登录功能，在登录界面只需要输入@BotFather建立的Bot的API Token就可以直接在该客户端上收发bot的信息。

（那我就在想是否可以让Pagermaid也这样，例如：【-BotToken 123456:ABC_xyz】来建立bot的私聊转发 / 【-BotToken Remove 123456:ABC_xyz】来取消bot的私聊转发 / 【-BotToken status】来查询所建立的bot私聊转发）毕竟是在自己服务器上，相对于@Liivegram想必会稳定些吧。

关于Nekogram源码：https://github.com/Nekogram/Android

================单纯的分割线================

【关于24小时在线】

是我在逛GitHub的时候无意中看到该项目（也不知是否失效），应该就是单纯的让自己Telegram账号一直在线吧（也不知是否理解有误）

是否可以让Pagermaid来管理这个项目（例如：-online true / -online false / -online status来管理）毕竟api_id / api_hash在登录Pagermaid时候就已经输入过了（不知是否可以实现）

GitHub项目源码地址：https://github.com/abusetelegram/AlwaysOnline-

**Comment by xtaodada** [comment]
@LucifinilCn 私聊转发bot  请移步 scp-079-pm 或者 pmcenter ， 24小时在线在做了在做了

**Comment by Jimmun** [comment]
【关于私聊转发bot】
这条建议 我局的这不和直接pm没有差别吗（

**Comment by xtaodada** [comment]
https://t.me/Pagermaid_Modify_Plugins/11

**Comment by Pentacene** [comment]
@listener(incoming=True, ignore_edited=True)
async def process_message(context):
    '''check_message'''
    # 始终在线
    try:
        await bot(functions.account.UpdateStatusRequest(offline=False))

**Comment by Pentacene** [comment]
始终在线 我的处理方法是

```from pagermaid import bot
@listener(incoming=True)
async def always_online(context):
    """始终在线"""
    try:
        await bot(functions.account.UpdateStatusRequest(offline=False))
    except:
        pass
```

收到一条消息后更新一下在线状态

**Comment by gchengyu** [comment]
@Pentacene 其实，始终在线只用在一个整天有一堆消息的群里开自动已读ghost就行了，我也不知道为什么，，
