### ISSUE TITLE
能否给animate和teletype等这种消息形态变换式的命令进行其他命令的嵌套

### ISSUE THREAD

**Issue by KorenKrita** [xtaodada/PagerMaid-Modify#22]
### 这是一个什么样的功能？
对消息编辑型命令进行命令嵌套
### 这个功能可以干什么？
比如说 -animate -help 这样-help就会以-animate的形式进行输出
再比如说 -tuxsay -sysinfo，-teletype -tuxsay -plugin status，等等
### 额外描述

**Comment by shzxm** [comment]
那你直接help以后，回复的形式嵌套不就完了么

**Comment by KorenKrita** [comment]
> 那你直接help以后，回复的形式嵌套不就完了么

这种消息编辑主要体现在消息通过一点点编辑进行弹出的对后面内容的未知感觉，如果一开始先发出了消息再通过回复来玩，感觉就像是在看一个已经知道了结局的剧一样。不知道比喻恰不恰当，可能对于-help这种感觉不是很明显。对于像-weather或者-ip，-google这种，我觉得体验感上来说确实会有意思些许。

只是忽然看到sendat可以进行命令嵌套联想到的玩法，消息的格式编辑和消息的内容均同时产出于bot自身，而不是通过回复去给bot键入一个内容再由bot进行格式编辑后输出。

**Comment by a-fruity-melon** [comment]
@KorenKrita sendat 是我写的，它支持套娃是我用特殊方法实现的，应该没法普遍推广。

最根本的问题在于底层的 telethon 不会再次捕获自己发出的消息。也许是出于预防死循环的考虑。

**Comment by KorenKrita** [comment]
> @KorenKrita sendat 是我写的，它支持套娃是我用特殊方法实现的，应该没法普遍推广。
> 
> 最根本的问题在于底层的 telethon 不会再次捕获自己发出的消息。也许是出于预防死循环的考虑。

了解了

**Comment by a-fruity-melon** [comment]
@KorenKrita 不过如果你想要给特定命令实现针对总命令集合的一个小子集的套娃的话，可以参考我在 sendat 里的做法：copy 一份目标函数的代码，并手动 parse、手动调用。
