### ISSUE TITLE
teletype在群组中遇到空格会产生错误

### ISSUE THREAD

**Issue by KorenKrita** [xtaodada/PagerMaid-Modify#26]
### BUG 发生地址
在群组中使用teletype遇到空格后会报错，在私聊及收藏夹内均可以正常运行
### 预期是什么？
正常编辑
### 实际发生了什么？
报错
### 额外信息（日志、报错等）

![](https://i.loli.net/2020/08/12/SnoRUKe5bHukT3D.jpg)

**Comment by xtaodada** [comment]
无法复现
