### ISSUE TITLE
验证码Invalid

### ISSUE THREAD

**Issue by Depos1t** [xtaodada/PagerMaid-Modify#3]
Please enter the code you received: 997xx
Invalid code. Please try again.

验证码是确实收到了的。验证码确认输入正确。api_hash和id也确认没问题。请问一下这是个什么问题呢？

**Comment by xtaodada** [comment]
@Depos1t 有时（或大部分时间），当您在服务器部署 PagerMaid-modify 时，登录会有问题，当出现了问题，请在应用程序的配置步骤配置唯一的 application key 和 hash ，然后在您的本地电脑上执行 python3 utils/mksession.py ，然后将生成的 pagermaid.session 文件复制到服务器对应目录。

**Comment by Depos1t** [comment]
是把整个pagermaid modify拉回本地电脑然后运行吗

**Comment by xtaodada** [comment]
随意，您也可以只拉取 utils/mksession.py 和 requirements.txt
