### ISSUE TITLE
能不能把tts命令的声音切换到中文声音.

### ISSUE THREAD

**Issue by shzxm** [xtaodada/PagerMaid-Modify#4]
能不能把tts命令的声音切换到中文声音.

**Comment by Jimmun** [comment]
@shzxm 有相同的需求

**Comment by shzxm** [comment]
或者说.脚本在哪.....可以自行根据需求修改

**Comment by yxkumad** [comment]
@shzxm @Jimmun 有相同的需求

**Comment by xtaodada** [comment]
目前暂无相关解决方案，欢迎 pr （

**Comment by shzxm** [comment]
https://cloud.google.com/text-to-speech?hl=zh-cn
这个api应该可以.实在不行让个人添加api就可以.免费的流量还是挺高的
> 目前暂无相关解决方案，欢迎pr（

**Comment by xtaodada** [comment]
升级后，` config.ini` 这样配置即可  `application_tts: "zh-CN" `

**Comment by GrassBlock1** [comment]
咱的之前就可以啊（@ytmip，手动艾特
