### ISSUE TITLE
好用

### ISSUE THREAD

**Issue by yuhuan-afk** [xtaodada/PagerMaid-Modify#5]
但是Redis出問題了

**Comment by Jimmun** [comment]
@yuhuan-afk 具體？

**Comment by yuhuan-afk** [comment]
@Jimmun
出错了呜呜呜 ~ Redis 好像离线了，无法执行命令。

**Comment by Jimmun** [comment]
@yuhuan-afk Redis未安裝
安裝教程：https://www.runoob.com/redis/redis-tutorial.html

**Comment by ItTooHard** [comment]
那是您没装。。。 直接apt/yum install redis

**Comment by GrassBlock1** [comment]
> @Jimmun
> 出错了呜呜呜 ~ Redis 好像离线了，无法执行命令。

怪我了怪我了，我没写（

**Comment by yuhuan-afk** [comment]
@GrassBlock1 close
