### ISSUE TITLE
-sticker 偷图会提示图片尺寸无效

### ISSUE THREAD

**Issue by xb0or** [xtaodada/PagerMaid-Modify#9]
![Screenshot_20200731-015237](https://user-images.githubusercontent.com/57210034/88956991-c9ddac80-d2d0-11ea-90ee-97f5d6c6f2ee.jpg)

**Comment by huazhuzhibai** [comment]
我也是这样，已经调整好但失败的图片  如果手动保存下来再手动上传就没有问题

**Comment by 815169876** [comment]
@huazhuzhibai 看来不光我一个

**Comment by 815169876** [comment]
@815169876 我擦   我怎么就进去了

**Comment by huazhuzhibai** [comment]
![image](https://user-images.githubusercontent.com/65559688/89006621-b9155100-d339-11ea-9aa8-913fc4897889.png)
尝试过更换回旧版本，更换系统版本后依旧是这样，机器人添加报尺寸错误，保存下来再手动上传没问题

**Comment by 815169876** [comment]
@huazhuzhibai 不止我一个啊

**Comment by haig233** [comment]
我也是

**Comment by a-fruity-melon** [comment]
@haig233 该 bug 为上游引入，请将 telethon 版本回退至 1.15.0：

python3 -m pip install "telethon==1.15.0"
